version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV:development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=pass
      - DB_NAME=test

    command: npm run dev
